/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsNavigationMenuIndexRouteImport } from './routes/components/navigation-menu/index'
import { Route as ComponentsAccordionIndexRouteImport } from './routes/components/accordion/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNavigationMenuIndexRoute =
  ComponentsNavigationMenuIndexRouteImport.update({
    id: '/components/navigation-menu/',
    path: '/components/navigation-menu/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsAccordionIndexRoute =
  ComponentsAccordionIndexRouteImport.update({
    id: '/components/accordion/',
    path: '/components/accordion/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/accordion/': typeof ComponentsAccordionIndexRoute
  '/components/navigation-menu/': typeof ComponentsNavigationMenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/accordion': typeof ComponentsAccordionIndexRoute
  '/components/navigation-menu': typeof ComponentsNavigationMenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/accordion/': typeof ComponentsAccordionIndexRoute
  '/components/navigation-menu/': typeof ComponentsNavigationMenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/components/accordion/' | '/components/navigation-menu/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components/accordion' | '/components/navigation-menu'
  id:
    | '__root__'
    | '/'
    | '/components/accordion/'
    | '/components/navigation-menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsAccordionIndexRoute: typeof ComponentsAccordionIndexRoute
  ComponentsNavigationMenuIndexRoute: typeof ComponentsNavigationMenuIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/navigation-menu/': {
      id: '/components/navigation-menu/'
      path: '/components/navigation-menu'
      fullPath: '/components/navigation-menu/'
      preLoaderRoute: typeof ComponentsNavigationMenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/accordion/': {
      id: '/components/accordion/'
      path: '/components/accordion'
      fullPath: '/components/accordion/'
      preLoaderRoute: typeof ComponentsAccordionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsAccordionIndexRoute: ComponentsAccordionIndexRoute,
  ComponentsNavigationMenuIndexRoute: ComponentsNavigationMenuIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
